#!/bin/bash

# Create the file with the desired name and content
echo "Best School" > '*\\'"Best School"\'\\*$\?\*\*\*\*\*:)'

# Add a newline at the end of the file
echo >> '*\\'"Best School"\'\\*$\?\*\*\*\*\*:)'
